package com.example.demo.mybatis;

import java.io.IOException;
import java.io.InputStream;

import com.example.demo.model.User;
import com.example.demo.mybatis.mapper.UserMapper;
import com.example.demo.mybatis.mapper.UserMapperAnnotation;

import org.apache.ibatis.io.Resources;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;
import org.junit.jupiter.api.Test;

public class MybatisTest {

    public SqlSessionFactory getSqlSessionFactory() throws IOException {
        String resource = "com/example/demo/mybatis/mybatis-config.xml";
        InputStream inputStream = Resources.getResourceAsStream(resource);
        return new SqlSessionFactoryBuilder().build(inputStream);
    }

    @Test
    public void testSelectUser() {
        SqlSession session = null;
        try {
            SqlSessionFactory sqlSessionFactory = getSqlSessionFactory();
            session = sqlSessionFactory.openSession();
            User user = session.selectOne("getUserById", 5);
            System.out.println(user);
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            if (session != null)
                session.close();
        }
    }

    @Test
    public void testMapperInterface() {
        SqlSession session = null;
        try {
            SqlSessionFactory sqlSessionFactory = getSqlSessionFactory();
            session = sqlSessionFactory.openSession();
            UserMapper mapper = session.getMapper(UserMapper.class);
            User user = mapper.getUserById(4);
            System.out.println(user);
            // a proxy class generated by mybatis
            System.out.println(mapper.getClass());
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            if (session != null)
                session.close();
        }
    }

    @Test
    public void testMapperInterfaceAnnotation() {
        SqlSession session = null;
        try {
            SqlSessionFactory sqlSessionFactory = getSqlSessionFactory();
            session = sqlSessionFactory.openSession();
            UserMapperAnnotation mapper = session.getMapper(UserMapperAnnotation.class);
            User user = mapper.getUserById(7);
            System.out.println(user);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (session != null) {
                session.close();
            }
        }
    }
}