package com.example.demo.mybatis;

import java.io.IOException;
import java.io.InputStream;

import com.example.demo.model.User;
import com.example.demo.mybatis.dao.UserDao;

import org.apache.ibatis.io.Resources;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;
import org.junit.jupiter.api.Test;

public class MybatisTest {

    public SqlSessionFactory getSqlSessionFactory() throws IOException {
        String resource = "mybatis/mybatis-config.xml";
        InputStream inputStream = Resources.getResourceAsStream(resource);
        return new SqlSessionFactoryBuilder().build(inputStream);
    }

    @Test
    public void testSelectUser() {
        SqlSession session = null;
        try {
            SqlSessionFactory sqlSessionFactory = getSqlSessionFactory();
            session = sqlSessionFactory.openSession();
            User user = session.selectOne("getUserById", 5);
            System.out.println(user);
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            if (session != null)
                session.close();
        }
    }

    @Test
    public void testDaoInterface() {
        SqlSession session = null;
        try {
            SqlSessionFactory sqlSessionFactory = getSqlSessionFactory();
            session = sqlSessionFactory.openSession();
            UserDao dao = session.getMapper(UserDao.class);
            User user = dao.getUserById(4);
            System.out.println(user);
            // a proxy class generated by mybatis
            System.out.println(dao.getClass());
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            if (session != null)
                session.close();
        }
    }
}